(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)




<<Quaternions`
<<PhysicalConstants`


thePathToTwo[theFourOptions_]:={

case[1]=Sqrt[theFourOptions];
case[1]=case[1]//N;
case[2]=Sqrt[case[1] + Sqrt[case[1]]];
case[2]=case[2]//N;
case[3]=Sqrt[case[2] + Sqrt[case[2]+ Sqrt[case[2]]]];
case[4]=Sqrt[case[3] + Sqrt[case[3]+ Sqrt[case[3]+Sqrt[case[3]]]]];
case[5]=Sqrt[case[4] + Sqrt[case[4]+ Sqrt[case[4]+Sqrt[case[4]+ Sqrt[case[4]]]]]];
case[6]=Sqrt[case[5] + Sqrt[case[5]+ Sqrt[case[5]+Sqrt[case[5]+ Sqrt[case[5]+ Sqrt[case[5]]]]]]];
case[7]=Sqrt[case[6] + Sqrt[case[6]+ Sqrt[case[6]+Sqrt[case[6]+ Sqrt[case[6]+ Sqrt[case[6]+ Sqrt[case[6]]]]]]]];
case[8]=Sqrt[case[7] + Sqrt[case[7]+ Sqrt[case[7]+Sqrt[case[7]+ Sqrt[case[7]+ Sqrt[case[7]+ Sqrt[case[7]+ Sqrt[case[7]]]]]]]]];
case[9]=Sqrt[case[8] + Sqrt[case[8]+ Sqrt[case[8]+Sqrt[case[8]+ Sqrt[case[8]+ Sqrt[case[8]+ Sqrt[case[8]+ Sqrt[case[8] + Sqrt[case[8]]]]]]]]]];
Table[case[n],{n,1,9}];
}



oneDimVectorCase[thisOneDimVectorCase_]:={
Sqrt[thisOneDimVectorCase],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]],
Sqrt[thisOneDimVectorCase + Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase+ Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]+Sqrt[thisOneDimVectorCase]]]]]]]



}



(*particleTableWorking = Prepend[Table[Prepend[ParticleData[Extract[theParticleDataSelectedParticlesWorking,i],#1]&/@theParticleDataPropertiesWorking ,Extract[theParticleDataSelectedParticlesWorking,i]],{i,Length[theParticleDataSelectedParticlesWorking]}],
Prepend[ParticleData["Properties"],"ParticleName"]
];*)



